name: Build SDKDumperProject

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.26.4'
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -S ../SDKDumperProject -B . -DCMAKE_BUILD_TYPE=Release
      - name: Build SDKDumper
        run: |
          cd build
          cmake --build . --config Release --target SDKDumper
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SDKDumper-bin
          path: build/bin/SDKDumper.dll
